# Generated by Django 3.1 on 2020-09-10 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_nick_nick_using'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nick',
            name='nick_using',
        ),
    ]
