# Generated by Django 3.1 on 2020-08-25 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200825_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='deadline_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_voting',
            field=models.BooleanField(default=True),
        ),
    ]
