# Generated by Django 3.0.5 on 2020-08-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=30)),
                ('professor', models.CharField(max_length=10)),
                ('separation', models.CharField(max_length=10)),
            ],
        ),
    ]
