# Generated by Django 3.0.5 on 2020-08-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='separation',
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_title',
            field=models.TextField(default='popo'),
            preserve_default=False,
        ),
    ]
