# Generated by Django 3.0.5 on 2020-08-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_eval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='professor',
            new_name='lecture_room',
        ),
    ]
