# Generated by Django 3.1 on 2020-08-26 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20200819_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eval',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='eval',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eval',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eval',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
