# Generated by Django 3.1 on 2020-08-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20200826_1357'),
        ('crud', '0006_auto_20200826_1429'),
    ]

    operations = [
    ]
