# Generated by Django 3.0.5 on 2020-08-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_remove_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='my_class',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'AI'), (1, 'CLOUD'), (2, 'BIGDATA'), (3, 'IOT')], default=1),
        ),
    ]
